### ISSUE TITLE
fix PointerLockControls when webxr emulator is not present

### ISSUE THREAD

**Issue by feiss** [MozillaReality/hello-webxr#52]

**Comment by fernandojsg** [comment]
If we are not presenting or in debug mode, pointerlock should not be used

**Comment by elolelo** [comment]
I see on the live version - there is an issue with PointerLockControl. 
<img width="1440" alt="Screenshot 2022-09-02 at 16 54 41" src="https://user-images.githubusercontent.com/32453496/188177808-4b3d4122-283a-430f-8001-8d9bff889a9f.png">

How should I test changes I've made to this project from my local server without pointerlockcontrol?
