### ISSUE TITLE
Text antialiasing and render order

### ISSUE THREAD

**Issue by lojjic** [MozillaReality/hello-webxr#67]
Certain angles give poor text antialising, due to the default sorting of transparent meshes sometimes rendering the text before its background plane. Example:

![image](https://user-images.githubusercontent.com/138124/73017456-1786d300-3ddd-11ea-8366-1cae252cdd31.png)

This could be brute-forced by setting a `renderOrder` on the text meshes, but that can sometimes cause other issues with other objects in the scene. As the author of the [`TextMesh`](https://github.com/protectwise/troika/tree/master/packages/troika-3d-text) library being used here, I'm very interested in coming up with a better solution that is more ergonomically friendly if possible, and would welcome input and ideas on that. 

Some related thoughts here, where I suggest a way to control the local origin to ensure correct depth-sorting: https://github.com/protectwise/troika/issues/6#issuecomment-573233245

**Comment by lojjic** [comment]
OK it took me a bit to get the local dev server to work, but once I did I can verify that the brute-force approach of setting `renderOrder` does fix the ugly antialiasing issue here. At its simplest, that's just adding:

`textMesh.renderOrder = 1;`

...(or any other positive number) in SDFTextSystem.js, either as a hardcoded value for every TextMesh instantiated, or as an updateable value of the Text component to control it individually.

As I mentioned this isn't totally foolproof, and can cause other artifacts when other transparent objects come in front of the text, but IMO that's much better than the current situation so I'd recommend implementing this brute-force fix for now. I'm happy to open a PR if there's agreement.

In the meantime, I do think I have a more robust and ergonomic solution in mind, but I'll need some time to prove that out.

**Comment by joshmarinacci** [comment]
I'm curious of setting renderOrder=1 has any performance implications.

**Comment by lojjic** [comment]
> I'm curious of setting renderOrder=1 has any performance implications.

I don't _think_ there should be any negative impact. It just moves those objects to the end of Three.js's internal sorted array of transparent objects. It shouldn't increase the GPU load at all. 

There may be a _very_ slight positive impact due to the draw calls for text meshes being bundled together in a row, which avoids some program switching. But with this few scene objects that's not going to be noticeable.

**Comment by fernandojsg** [comment]
Thanks for taking a look at this! And I agree, `renderOrder` should not affect performance.
Feel free to open a PR with this workaround in the meantime ^_^
