### ISSUE TITLE
Teleport beam is invisible while it overrides other transparent objects

### ISSUE THREAD

**Issue by BOLL7708** [MozillaReality/hello-webxr#69]
The teleport beam competes with other transparent objects, like the logo and the speech bubbles, this while most apparently being completely invisible. I tried force reloading the page multiple times to see if I was missing data, but it stayed the same. It is a bit distracting and feels like it's malfunctioning. Also creates something akin to depth disparity as it looks like a near field object, but creates a hole through other things to the background. It's weird.

![20200124005916_1_vr](https://user-images.githubusercontent.com/12276837/73034629-bf37eb80-3e45-11ea-8f71-a51bcb78e831.jpg)
![20200124010043_1_vr](https://user-images.githubusercontent.com/12276837/73034904-a2e87e80-3e46-11ea-8624-6be659b94aac.jpg)

Using a Valve Index system with SteamVR Beta 1.10.6 running Firefox 72.0.2 on Windows 10 Pro 1809.

**Comment by feiss** [comment]
fixed via #c3e22097896fefd696b0dbaf52d59362a6971fda
