### ISSUE TITLE
First example spherical panorama appears to have a wonky stereo offset

### ISSUE THREAD

**Issue by BOLL7708** [MozillaReality/hello-webxr#70]
While the first panorama has nice near field objects, it also appears to be very off in the stereo offset. Every time I open it I get double vision until my eyes adjust, and then it's uncomfortable. I do have convergence insufficiency so near field is harder, but this feels straight wrong?! 😅 Or is it perhaps the vergence-accommodation conflict that makes it uncomfortable, hmm.
![20200124004716_1](https://user-images.githubusercontent.com/12276837/73035026-112d4100-3e47-11ea-969c-e3c2b220c099.jpg)

Using a Valve Index system with SteamVR Beta 1.10.6 running Firefox 72.0.2 on Windows 10 Pro 1809.

**Comment by feiss** [comment]
You are completely right. Stereo 360º don't work for me at all, actually. Do you know of any that works at all distances, without double vision? IMHO, I think this is a limitation of the stereo 360s. You don't have data to fill the gaps behind objects, nor paralax..  

I looked for different panoramas, and this is the best I found. For example, the one in the three.js examples: https://threejs.org/examples/?q=vr#webxr_vr_panorama  feels worse (at least for me)

Happy to reopen this issue if we found a better panorama.
