### ISSUE TITLE
new SDFTextSystem error trying to run at localhost:8080

### ISSUE THREAD

**Issue by arturitu** [MozillaReality/hello-webxr#71]
I just clone it and 'npm install', 'npm start' and this message appeared:
![image](https://user-images.githubusercontent.com/5744112/73058686-693e6480-3e94-11ea-96ab-43c8d083bbfe.png)

**Comment by lojjic** [comment]
I ran into this too. Not sure the exact root cause, but I was able to work around it by temporarily commenting out the `presets: ['@babel/preset-env']` within webpack.config.js.

**Comment by bmf** [comment]
Is this related to #73 ?

**Comment by lojjic** [comment]
@bmf No, this issue existed prior to that fix.
