### ISSUE TITLE
hangs loading on iOS in Safari, Firefox, etc

### ISSUE THREAD

**Issue by blairmacintyre** [MozillaReality/hello-webxr#72]
I believe there are two things going on, this will be easy to check for someone on the team with an iOS device and mac.

Run it on Safari with the debugger open, there are two issues:
-  In the safari console, there's an error "this.domElement.requestPointerLock is not a function. (In 'this.domElement.requestPointerLock()', 'this.domElement.requestPointerLock' is undefined)hello-webxr:536".  I don't know if this is stopping it from proceeding
​-Also, a warning "No device motion or orientation events will be fired until permission has been requested and granted.hc — js:40:202" in webxr-polyfill.module.js ... but, there is no longer a permission in Safari for enabling device motion,  I just submitted an issue on the webxr-polyfill for this.  Again, I don't know if this is the cause.

I get the same behavior in Firefox for iOs, and in my WebXR Viewer for iOS based on safari.

**Comment by blairmacintyre** [comment]
Still broken

**Comment by fernandojsg** [comment]
I just checked it on Safari on mac and I get a different error, it seems like it's related to the draco decoder maybe? /cc @feiss 
![image](https://user-images.githubusercontent.com/782511/73664960-99f67900-46a0-11ea-9b65-4c92d5364903.png)

Can you try this demo to see if you get the same error regarding `requestPointerLock`?  https://threejs.org/examples/?q=pointerlock#misc_controls_pointerlock
Regarding the second issue it seems like a webxr-polyfill issue, but I don't have any iOS device so I can't really test it there :\

**Comment by feiss** [comment]
In my case (MacOS Safari), I just have 4 warnings and stops loading at about 90% (no errors)  :?

**Comment by PixelPartner** [comment]
It also blocks at 90% (same reasons?) in Mozilla's own XRViewer iOS-App (v2.00)
