### ISSUE TITLE
Fails to load on Oculus Quest Browser, 404 error on asset

### ISSUE THREAD

**Issue by rotoglup** [MozillaReality/hello-webxr#83]
Seen while trying to explore the online version at https://mixedreality.mozilla.org/hello-webxr/, which worked fine about 2 weeks ago.

Using the Chrome remote debugger I get to see the following message : 

> `/hello-webxr/assets/beamfx.basis`
> Failed to load resource: the server responded with a status of 404 ()
> bundle.js:72804 Error loading asset ProgressEvent

**Comment by rotoglup** [comment]
Works again now, closing

**Comment by flagstone78** [comment]
I have the same issue except on the chrome browser on my pixel 3a phone.

**Comment by rotoglup** [comment]
I've just tested, works fine here with chrome 81 on Pixel 3a + Android 10 🤔
