### ISSUE TITLE
Room Load Failed On Initial Run: Uncaught Type Error: c.getName is not a Function 

### ISSUE THREAD

**Issue by shiyu99** [MozillaReality/hello-webxr#89]
Hi!

First, thank you all so much for this amazing open-source project!
I tried to run "npm start" and open the project up in the browser after forking, cloning, and "npm install".
However, the room wasn't loading. I tried the debugger tools and it showed "Uncaught Type Error: c.getName is not a Function" in the System.js file.  The file hierarchy is [ node_modules-> ecsy/src -> RemoveDevTools-> System.js".
![image](https://user-images.githubusercontent.com/53148393/93124558-cabb7980-f697-11ea-9306-e08af75a046d.png)
This is the call stack.
![image](https://user-images.githubusercontent.com/53148393/93124872-4caba280-f698-11ea-915c-085a95c030bc.png)

Did anyone run into this problem before? If so, how did you solve it? 
Or did anyone have any advice? 

Thanks a lot!

**Comment by shiyu99** [comment]
My professor said it might be because I built it on a different Node / other dependencies version when I did "npm install" than the original Node version used by the project. Does anyone know what are the versions of the dependencies this original project is running on? Many Thanks!

**Comment by feiss** [comment]
Hi Shiyu,

Sorry for the delay in answering.

The problem was that the newest versions of the ECSY library break the app. It seems that the latest working version is 0.2.6. I've pushed the change, but you can do it yourself in your fork by editing `package.json` and replacing line 33 for this one: `"ecsy": "0.2.6",`

I hope you still get on time to the deadline!

**Comment by feiss** [comment]
closed via https://github.com/MozillaReality/hello-webxr/commit/c0924d1f29f6a1e388fae8f6db1e73e71634f7df

**Comment by shiyu99** [comment]
Thank you so much Diego, this is very helpful!
