### ISSUE TITLE
in all Blender files graphics are missing 

### ISSUE THREAD

**Issue by r23** [MozillaReality/hello-webxr#90]
Hello,

Thanks for the great project. Unfortunately I have a small problem with the Blender files.

In all Blender files graphics are missing.

Example angel.blend

Path 'C:\xampp\htdocs\git\hello-webxr\assets\pg_floor_lm.png' not found
Path 'C:\xampp\htdocs\Downloads\baptismal-angel-kneeling\source\angelyy\angelyy01.jpg' not found
Path 'C:\xampp\htdocs\hello-webxr\assets\blender\flare.psd' not found
Path 'C:\xampp\htdocs\hello-webxr\assets\blender\panel.psd' not found
Path 'C:\xampp\htdocs\hello-webxr\assets\blender\pano.jpg' not found
Path 'C:\xampp\htdocs\git\hello-webxr\assets\pg_door_lm.png' not found
Path 'C:\xampp\htdocs\hello-webxr\assets\blender\travertine2.jpg' not found

All Blender files have faulty paths to graphics that are not available on our system.

![grafik](https://user-images.githubusercontent.com/396063/101241820-d4360a00-36f9-11eb-8e7a-007325d1b5bd.png)

You can prevent this by using Blender
External Data => Automatically Pack into .blend     is selected.

kind regards

Ralf

**Comment by mauriziop81** [comment]
Hi,
I have the same  issue, how can to resolve it?

**Comment by Gowtham029** [comment]
@mauriziop81 you got any solution?
